name: Rust CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.31.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          working-directory: "native/lingua_nif"
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          working-directory: "native/lingua_nif"
          command: build

      - uses: actions-rs/cargo@v1
        with:
          working-directory: "native/lingua_nif"
          command: test

      - uses: actions-rs/cargo@v1
        with:
          working-directory: "native/lingua_nif"
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          working-directory: "native/lingua_nif"
          command: clippy
          args: -- -D warnings