name: Rust CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  working-directory: native/lingua_nif

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.31.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          working-directory: ${{env.working-directory}}
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build
          working-directory: ${{env.working-directory}}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          working-directory: ${{env.working-directory}}

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          working-directory: ${{env.working-directory}}

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
          working-directory: ${{env.working-directory}}